### ISSUE TITLE
My PC happen to crash while downloading

### ISSUE THREAD

**Issue by 99keyz** [SenZmaKi/Senpwai#4] opened 2023-06-24 19:50 UTC
y PC happen to crash while downloading Demon Slayer, and now when I go back to download it again it crashes the app.

**Comment by SenZmaKi** [comment] 2023-06-25 00:59
Which season of demon slayer exactly were you trying to download exactly, and what are your download configuration settings i.e the quality, sub or dub and the download folder.  If possible send a video of the app crashing cause it usually includes some important error messages.

Also I'm working on a way better version so please bear with me if I'm not able to immediately fix the crash.

**Comment by 99keyz** [comment] 2023-06-25 02:11
I will get you a video later, my settings are Dub at 1080p, to Drive D:\Plex Media\Anime\Demon Slayer. Is there any Directory I can follow so I can reset the app, such as a config in documents. honestly have been searching.

I appreciate all the work you are doing to make my hoarding easier. really looking foward to that new version.

**Comment by 99keyz** [comment] 2023-06-27 07:25
https://github.com/SenZmaKi/Senpwai/assets/109197989/ab81bcc3-3278-4bfe-b872-7a11767a751d

**Comment by SenZmaKi** [comment] 2023-06-27 17:17
Thanks for posting the video, ok I see what the problem is, usually on the download page in animepahe there are 6 links, 3 for dub and 3 for sub, then the three are divided up for 1080p, 720p and finally 360p. While making Senpwai I made the assumption that this will always be true and if dub is unavailable then there'd be just 3 links, but for some reason for that arc of demon slayer specifically, on the download page there are 9 links 6 for sub and 3 for dub. 

Since I only ever considered the existence of either 6 or 3 links, Senpwai is confused by the 9 links hence she crashes, in the upcoming "update" I am working on (Calling it an update is an understatement honestly) I handle the extraction of the links more flexibly. I can't make a fix for this issue specifically cause in the upcoming "update" it will be addressed, and I want to fix *all* the the occurring issues, bugs and crashes in this "update". I hope you can bear with me, it shouldn't take me more than a month. 

[You can find the details about the "update" here](url)
If you have ideas for any features you'd like to be implemented be sure to tell me

**Comment by 99keyz** [comment] 2023-06-28 07:44
Would it be appropriate to contact you through Reddit?

**Comment by SenZmaKi** [comment] 2023-06-28 08:18
sure I don't mind https://reddit.com/user/UzumaKiObaruto

**Comment by 99keyz** [comment] 2023-07-27 06:00
Ive had another crash while installing Urusei Yatsura. "the older version" didnt think it was worth another issue post

https://github.com/SenZmaKi/Senpwai/assets/109197989/1217cbf3-9f86-4c15-9deb-cbf9141f24ed

**Comment by SenZmaKi** [comment] 2023-07-27 13:55
Funny I just released the [new version](https://github.com/SenZmaKi/Senpwai/releases) today, I hope you like it.

**Closed** 2023-07-27 20:00 UTC
